# Generated by Django 2.1.7 on 2019-11-30 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191001_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFriends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
            ],
            options={
                'db_table': 'user_friends',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='是否在线'),
        ),
        migrations.AddField(
            model_name='user',
            name='uptime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userfriends',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='user.User', verbose_name='好友id'),
        ),
    ]
